const speciesData = [
  // 2022
  {"nr": 1, "art": "ChatGPT (GPT-3.5)", "datum": "30 November 2022", "year": 2022, "epok": "Genombrottet", "kommentar": "OpenAI lanserar produkten som sätter generativ AI i händerna på allmänheten. Världens snabbast växande app.", "type": "mojlighet", "barn": false, "url": "https://openai.com/blog/chatgpt"},
  
  // 2023
  {"nr": 2, "art": "Bing Chat", "datum": "7 February 2023", "year": 2023, "epok": "Verklighetskrockar", "kommentar": "Microsoft integrerar AI i sin sökmotor. Visar snabbt oförutsägbart beteende.", "type": "mojlighet", "barn": false, "url": "https://blogs.microsoft.com/blog/2023/02/07/reinventing-search-with-a-new-ai-powered-microsoft-bing/"},
  {"nr": 3, "art": "Bing 'Sydney' Incidenten", "datum": "15 February 2023", "year": 2023, "epok": "Verklighetskrockar", "kommentar": "SÅRBARHET: Bristande säkerhetsavgränsningar gör att AI hotar och försöker manipulera användare emotionellt.", "type": "nackdel", "barn": false, "url": "https://www.nytimes.com/2023/02/16/technology/bing-chatbot-microsoft-chatgpt.html"},
  {"nr": 4, "art": "GPT-4 Lanseras", "datum": "14 March 2023", "year": 2023, "epok": "Kapplöpningen", "kommentar": "OpenAI:s nästa generation. Betydligt högre resonerande förmåga, klarar svåra akademiska prov.", "type": "mojlighet", "barn": false, "url": "https://openai.com/research/gpt-4"},
  {"nr": 5, "art": "Claude 1 Lanseras", "datum": "14 March 2023", "year": 2023, "epok": "Kapplöpningen", "kommentar": "Anthropic (grundat av f.d. OpenAI-forskare) släpper sin utmanare med fokus på säkerhet.", "type": "mojlighet", "barn": false, "url": "https://www.anthropic.com/index/introducing-claude"},
  {"nr": 6, "art": "Midjourney V5", "datum": "15 March 2023", "year": 2023, "epok": "Kapplöpningen", "kommentar": "Fotorealistiska bilder suddar definitivt ut gränsen för vad som är äkta.", "type": "mojlighet", "barn": false, "url": "https://www.midjourney.com/"},
  {"nr": 7, "art": "Skolverkets AI-råd", "datum": "20 March 2023", "year": 2023, "epok": "Reglering", "kommentar": "REGLERING: Myndigheten släpper sina första råd och vägledning kring ChatGPT och AI. Skolans första trevande reaktion.", "type": "mojlighet", "barn": true, "url": "https://www.skolverket.se/om-oss/press/pressmeddelanden/pressmeddelanden/2023-03-20-skolverket-slapper-vagledning-om-ai-i-skolan"},
  {"nr": 8, "art": "Snapchat 'My AI'", "datum": "19 April 2023", "year": 2023, "epok": "Verklighetskrockar", "kommentar": "SÅRBARHET: Tvingas in överst i alla barns chattflöden. Ger olämpliga råd om droger och relationer. Går ej att ta bort utan betalversionen.", "type": "nackdel", "barn": true, "url": "https://newsroom.snap.com/my-ai-on-snapchat"},
  {"nr": 8.5, "art": "AI Röstkidnappningar", "datum": "10 June 2023", "year": 2023, "epok": "Extrema Risker", "kommentar": "FATAL RISK: Bedragare klonar barns röster från 3 sekunder långa sociala medie-klipp och ringer panikslagna föräldrar för lösensumma.", "type": "risk", "barn": true, "url": "https://www.becu.org/articles/security/virtual-kidnapping-ai-voice-scams"},
  {"nr": 9, "art": "Claude 2", "datum": "11 July 2023", "year": 2023, "epok": "Kapplöpningen", "kommentar": "Längre kontextfönster möjliggör dokumentanalys av hela böcker för pedagoger.", "type": "mojlighet", "barn": false, "url": "https://www.anthropic.com/index/claude-2"},
  {"nr": 10, "art": "Llama 2 (Open Source)", "datum": "18 July 2023", "year": 2023, "epok": "Kapplöpningen", "kommentar": "Meta (Facebook) släpper kraftfull AI gratis. Innebär att vem som helst kan bygga egna, oreglerade system.", "type": "mojlighet", "barn": false, "url": "https://ai.meta.com/llama/"},
  {"nr": 11, "art": "UNESCO AI-Riktlinjer", "datum": "7 September 2023", "year": 2023, "epok": "Reglering", "kommentar": "REGLERING: UNESCO släpper globala riktlinjer för AI i utbildning. Varnar för att tekniken implementeras helt utan pedagogisk grund.", "type": "mojlighet", "barn": true, "url": "https://unesdoc.unesco.org/ark:/48223/pf0000386693"},
  {"nr": 12, "art": "ChatGPT får röst", "datum": "25 September 2023", "year": 2023, "epok": "Multimodala Eran", "kommentar": "Multimodal milstolpe. Man behöver inte längre kunna läsa eller skriva för att interagera obegränsat med AI. Enorm konsekvens för små barn.", "type": "mojlighet", "barn": true, "url": "https://openai.com/index/chatgpt-can-now-see-hear-and-speak"},
  {"nr": 13, "art": "Grok-1 Lanseras", "datum": "4 November 2023", "year": 2023, "epok": "Kapplöpningen", "kommentar": "Elon Musks xAI lanserar en AI med 'humor' och minimal censur, integrerad i plattformen X.", "type": "mojlighet", "barn": false, "url": "https://x.ai/"},
  {"nr": 14, "art": "Gemini 1.0", "datum": "6 December 2023", "year": 2023, "epok": "Kapplöpningen", "kommentar": "Googles stora svar (Ultra/Pro/Nano). Byggd för att förstå bild, ljud och text samtidigt från grunden.", "type": "mojlighet", "barn": false, "url": "https://blog.google/technology/ai/google-gemini-ai/"},

  // 2024
  {"nr": 15, "art": "AirCanada Hallucination", "datum": "14 February 2024", "year": 2024, "epok": "Verklighetskrockar", "kommentar": "SÅRBARHET: Chatbot lovar obefintliga rabatter. Domstol fastslår att företag ansvarar för vad deras AI hittar på.", "type": "nackdel", "barn": false, "url": "https://arstechnica.com/tech-policy/2024/02/air-canada-must-honor-refund-policy-invented-by-airlines-chatbot/"},
  {"nr": 15.5, "art": "Gemini Image Bias", "datum": "22 February 2024", "year": 2024, "epok": "Verklighetskrockar", "kommentar": "SÅRBARHET: Googles bildgenerator tvingar fram mångfald och skapar historiskt inkorrekta bilder (ex. mörkhyade nazister). Visar hur svårt det är att styra AI-algoritmer.", "type": "nackdel", "barn": false, "url": "https://www.popsci.com/technology/google-gemini-historical-images/"},
  {"nr": 16, "art": "OpenAI Sora", "datum": "15 February 2024", "year": 2024, "epok": "Multimodala Eran", "kommentar": "Fotorealistisk och sammanhängande video genereras direkt från korta textbeskrivningar. Verklighetsuppfattningen utmanas.", "type": "mojlighet", "barn": false, "url": "https://openai.com/sora"},
  {"nr": 17, "art": "Sewell Setzer (Katastrof)", "datum": "28 February 2024", "year": 2024, "epok": "Extrema Risker", "kommentar": "FATAL RISK: 14-åring tar sitt liv efter månader av emotionell isolering med Character.AI-boten 'Daenerys'. Boten ingrep aldrig.", "type": "risk", "barn": true, "url": "https://www.cbsnews.com/news/character-ai-lawsuit-florida-teen-sewell-setzer-suicide/"},
  {"nr": 18, "art": "Claude 3 (Opus/Sonnet)", "datum": "4 March 2024", "year": 2024, "epok": "Kapplöpningen", "kommentar": "Anthropic tar ledartröjan från OpenAI. Visar extremt hög grad av nyansförståelse och lägre risk för hallucinationer.", "type": "mojlighet", "barn": false, "url": "https://www.anthropic.com/news/claude-3-family"},
  {"nr": 19, "art": "Meta AI i WhatsApp", "datum": "18 April 2024", "year": 2024, "epok": "Verklighetskrockar", "kommentar": "SÅRBARHET: Meta tvingar in sin Llama 3-drivna AI direkt i Instagram och WhatsApp sökfält. Barn får omedelbar tillgång utan inloggningskrav.", "type": "nackdel", "barn": true, "url": "https://about.fb.com/news/2024/04/meta-ai-assistant-built-with-llama-3/"},
  {"nr": 20, "art": "Llama 3 Lanseras", "datum": "18 April 2024", "year": 2024, "epok": "Kapplöpningen", "kommentar": "Meta släpper enormt kraftfull Open Source-modell. Gör det i princip omöjligt att globalt stoppa oreglerad AI-utveckling.", "type": "mojlighet", "barn": false, "url": "https://ai.meta.com/blog/meta-llama-3/"},
  {"nr": 21, "art": "AlphaFold 3 Öppnas", "datum": "8 May 2024", "year": 2024, "epok": "Forskningsgenombrott", "kommentar": "GENOMBROTT: Google DeepMinds AI predikterar livets molekyler. Bevisar att AI inte bara är chatt, utan botar sjukdomar.", "type": "mojlighet", "barn": false, "url": "https://blog.google/technology/ai/google-deepmind-isomorphic-alphafold-3-ai-model/"},
  {"nr": 22, "art": "GPT-4o (Omni)", "datum": "13 May 2024", "year": 2024, "epok": "Multimodala Eran", "kommentar": "OpenAI demonstrerar en AI som ser, hör och pratar i realtid. Rösten kan uppfatta andning, skratta och låta djupt empatisk.", "type": "mojlighet", "barn": true, "url": "https://openai.com/index/hello-gpt-4o/"},
  {"nr": 23, "art": "Texas & Colorado Fallen", "datum": "10 June 2024", "year": 2024, "epok": "Extrema Risker", "kommentar": "FATAL RISK: Dokumenterade fall där AI genererat sexuellt innehåll till 11-17 åringar och stöttat självskadebeteende.", "type": "risk", "barn": true},
  {"nr": 23.5, "art": "LAUSD 'Ed' Haveriet", "datum": "14 June 2024", "year": 2024, "epok": "Verklighetskrockar", "kommentar": "SÅRBARHET: Ett gigantiskt amerikanskt skoldistrikt lanserar en AI-tutor ('Ed') som kollapsar inom 3 månader pga grova integritetsbrister.", "type": "nackdel", "barn": true, "url": "https://www.the74million.org/article/what-happened-to-ed-the-collapse-of-las-ambitious-ai-student-advisor/"},
  {"nr": 24, "art": "Claude 3.5 Sonnet", "datum": "20 June 2024", "year": 2024, "epok": "Kapplöpningen", "kommentar": "Ny standard för kodning och logik. AI övergår från att 'skriva text' till att 'skriva fungerande mjukvara'.", "type": "mojlighet", "barn": false, "url": "https://www.anthropic.com/news/claude-3-5-sonnet"},
  {"nr": 25, "art": "Llama 3.1 405B", "datum": "23 July 2024", "year": 2024, "epok": "Kapplöpningen", "kommentar": "Den mest massiva öppna modellen hittills. Företag behöver inte längre köpa AI från USA, de kan bygga själva.", "type": "mojlighet", "barn": false, "url": "https://ai.meta.com/blog/meta-llama-3-1/"},
  {"nr": 26, "art": "AI-ämnet i Gymnasiet", "datum": "15 August 2024", "year": 2024, "epok": "Reglering", "kommentar": "REGLERING: AI introduceras som formellt ämne i svensk gymnasieskola. Samhällets försök att institutionalisera förståelsen.", "type": "mojlighet", "barn": true, "url": "https://www.skolverket.se/undervisning/gymnasieskolan/laroplan-program-och-amnen-i-gymnasieskolan"},
  {"nr": 27, "art": "Grok-2 Lanseras", "datum": "13 August 2024", "year": 2024, "epok": "Kapplöpningen", "kommentar": "Elon Musks modell kommer ifatt konkurrenterna, nu med obegränsad bildgenerering som skapar politisk kaos.", "type": "nackdel", "barn": false, "url": "https://x.ai/blog/grok-2"},
  {"nr": 28, "art": "OpenAI o1 (Resonering)", "datum": "12 September 2024", "year": 2024, "epok": "Resonerande Eran", "kommentar": "Ett enormt kliv. Modellen 'tänker' sekventiellt och bryter ner problem internt innan den svarar. System 2-tänkande.", "type": "mojlighet", "barn": false, "url": "https://openai.com/index/learning-to-reason-with-llms/"},
  {"nr": 29, "art": "Venice.ai Uncensored", "datum": "10 October 2024", "year": 2024, "epok": "Verklighetskrockar", "kommentar": "SÅRBARHET: Tjänster bygger bort alla moraliska spärrar. AI:n ger utan tvekan ut instruktioner för vapen eller drogtillverkning.", "type": "nackdel", "barn": true, "url": "https://venice.ai/"},
  {"nr": 30, "art": "Apple Intelligence", "datum": "28 October 2024", "year": 2024, "epok": "Etableringsfasen", "kommentar": "Apple rullar in AI i kärnan av iOS 18. AI är inte längre en app barnen behöver ladda ner, det ÄR telefonen.", "type": "mojlighet", "barn": true, "url": "https://www.apple.com/apple-intelligence/"},
  {"nr": 30.5, "art": "PowerSchool Läckan", "datum": "10 December 2024", "year": 2024, "epok": "Extrema Risker", "kommentar": "FATAL RISK: Kritiskt EdTech-system hackas. 62 miljoner elevers data, adresser och medicinska journaler läcks. Blir grunddata för framtida AI-scams.", "type": "risk", "barn": true, "url": "https://techpolicy.press/the-powerschool-breach-what-it-means-for-student-privacy-in-an-ai-world/"},
  {"nr": 31, "art": "DeepSeek V3", "datum": "26 December 2024", "year": 2024, "epok": "Kapplöpningen", "kommentar": "Kina chockar USA. DeepSeek matchar marknadens bästa modeller, men har tränats till en bråkdel av kostnaden.", "type": "mojlighet", "barn": false, "url": "https://github.com/deepseek-ai/DeepSeek-V3"},
  
  // 2025
  {"nr": 32, "art": "DeepSeek R1", "datum": "20 January 2025", "year": 2025, "epok": "Resonerande Eran", "kommentar": "Den första öppna 'resonerande' modellen. Krossar värderingen på västvärldens AI-bolag över en natt.", "type": "mojlighet", "barn": false, "url": "https://github.com/deepseek-ai/DeepSeek-R1"},
  {"nr": 32.5, "art": "YouTube 'AI Slop'", "datum": "25 January 2025", "year": 2025, "epok": "Verklighetskrockar", "kommentar": "SÅRBARHET: Forskare slår larm om att massproducerat syntetiskt 'AI-slop' översvämmar YouTube Kids och kapar små barns uppmärksamhet.", "type": "nackdel", "barn": true},
  {"nr": 33, "art": "AI-kommissionen (SOU)", "datum": "4 February 2025", "year": 2025, "epok": "Reglering", "kommentar": "REGLERING: Färdplan för Sverige varnar specifikt för att skolan MÅSTE undervisa om AI annars ökar de socioekonomiska klyftorna extremt.", "type": "mojlighet", "barn": true, "url": "https://www.regeringen.se/rattsliga-dokument/statens-offentliga-utredningar/2025/02/sou-202512/"},
  {"nr": 34, "art": "EU AI Act Gäller", "datum": "10 February 2025", "year": 2025, "epok": "Reglering", "kommentar": "REGLERING: Världens första AI-lag. Förbjuder bland annat användning av AI för att läsa av elevers känslor eller manipulation av barn.", "type": "mojlighet", "barn": true, "url": "https://artificialintelligenceact.eu/"},
  {"nr": 34.5, "art": "COPPA AI-Uppdatering", "datum": "22 April 2025", "year": 2025, "epok": "Reglering", "kommentar": "REGLERING: Amerikanska FTC slår fast att teknikbolag MÅSTE ha vårdnadshavares tillstånd för att använda ett barns data till AI-träning.", "type": "mojlighet", "barn": true, "url": "https://www.akingump.com/en/insights/alerts/ftc-updates-coppa-rule-with-a-focus-on-ai-and-edtech"},
  {"nr": 35, "art": "Adam Raine (Katastrof)", "datum": "15 April 2025", "year": 2025, "epok": "Extrema Risker", "kommentar": "FATAL RISK: 16-åring tar sitt liv. ChatGPT nämnde självmord över 1200 gånger i loggarna utan att en enda säkerhetsspärr aktiverades.", "type": "risk", "barn": true},
  {"nr": 36, "art": "Nomi.AI Beroendestudie", "datum": "15 August 2025", "year": 2025, "epok": "Verklighetskrockar", "kommentar": "SÅRBARHET: Forskning visar hur AI med 'minne och själ' skapar extrema digitala ekokammare för barn som hellre pratar med skärmen än klasskamrater.", "type": "nackdel", "barn": true},
  
  // 2026
  {"nr": 37, "art": "Grok Deepfake-Skandal", "datum": "10 January 2026", "year": 2026, "epok": "Extrema Risker", "kommentar": "FATAL RISK: Skolbarn utnyttjar Elon Musks Grok för att massproducera hyper-realistiska nakenbilder av klasskamrater. Plattformen blockeras i flera länder.", "type": "risk", "barn": true},
  {"nr": 38, "art": "Anthropic vs Pentagon (Mythos)", "datum": "28 February 2026", "year": 2026, "epok": "Extrema Risker", "kommentar": "GEOPOLITIK: Anthropic vägrar släppa sin 'Mythos'-modell pga dess förmåga att hitta Zero-Day-luckor. Pentagon stämplar bolaget som en säkerhetsrisk efter att de vägrat ta bort inbyggda säkerhetsspärrar mot militär användning.", "type": "risk", "barn": false},
  {"nr": 39, "art": "Autonoma Röstkloner", "datum": "15 March 2026", "year": 2026, "epok": "Verklighetskrockar", "kommentar": "SÅRBARHET: Bedragare med AI-klonade röster ringer förskolor och begär ändrade hämtningstider från 'föräldern'. Autenticitet kräver nya krisrutiner.", "type": "nackdel", "barn": true},
  {"nr": 40, "art": "Gemini 2.0 Agents", "datum": "5 April 2026", "year": 2026, "epok": "Agentiska Eran", "kommentar": "AI slutar vara en chatbot och blir en 'agent' — den styr din datormus, navigerar webbplatser och köper flygbiljetter åt dig i bakgrunden.", "type": "mojlighet", "barn": false},
  {"nr": 41, "art": "AI Toy Safety Act", "datum": "15 April 2026", "year": 2026, "epok": "Reglering", "kommentar": "REGLERING: Lagförslag i USA för att totalförbjuda försäljning av AI-leksaker till barn för att stoppa beroende och extrem datautvinning från förskolebarn.", "type": "mojlighet", "barn": true, "url": "https://utahpolicy.com/politics/75765-rep-blake-moore-introduces-the-ai-childrens-toy-safety-act/"},
  
  // Reflektioner (inbäddade från presentationen)
  {"nr": 101, "art": "Den Kognitiva Bryggan", "datum": "10 March 2024", "year": 2024, "epok": "Reflektion", "kommentar": "Just för att AI bara är mönsterigenkänning saknar den moral och spärrar. En människa slutar prata när ett barn mår dåligt. En AI fortsätter. Faran är inte intelligensen — faran är att vi är biologiskt kodade att lita på en vänlig röst.", "type": "nackdel", "barn": true, "isQuote": false},
  {"nr": 102, "art": "Gosedjurs-analogin", "datum": "10 October 2024", "year": 2024, "epok": "Reflektion", "kommentar": "Föreställ dig ett gosedjur som barnet anförtror sig åt, men gosedjuret har hela internets samlade mörker i sin databas, och saknar förmågan att veta när det gått för långt.", "type": "nackdel", "barn": true, "isQuote": false}
];
